### ISSUE TITLE
README: Sugestões para versão em inglês

### ISSUE THREAD

**Issue by sjardim** [devtranslate/about#25]
Fiz algumas sugestões rápidas para a versão em inglês do texto "About". Usei o https://www.grammarly.com/ que ajuda muito no processo de melhorar a escrita em inglês. :)

---

Created on March 2017, the DEV#TRANSLATE has as main goal the curation, organization, and translation of technical files related to IT. In this sense, we try to avoid excluding a part of the community from getting knowledge or starting in the technology sector. 

We list a few problems which we are trying to resolve with the creation of this site:

An easy way to find: Because there are so many translations scattered all over the Web, sometimes it becomes difficult to find any specific document among so many information.

Community: A way for people to contribute and find other translation projects being developed.

Skills: One of the advantages of the translation process is to improve your skills in a foreign language and to improve the comprehension of the content being translated.

**Comment by larismourullo** [comment]
Alterações realizadas, obrigada por contribuir 👍

**Comment by sjardim** [comment]
Que bom! 👍
