### ISSUE TITLE
 Create Template to Request Permission to Perform Translation

### ISSUE THREAD

**Issue by larismourullo** [devtranslate/about#3]
**Progress:**
- To Do ( ✔️ )
- In Progress ( ✔️ )
- Review ( ✔️ )
- Done ( ✔️ )

**Repository:**
[devtranslate/medium/PERMISSION.md](https://github.com/devtranslate/medium/blob/master/PERMISSION.md)

**Description**
You need to create a template for users to send to authors to try to get permission to perform a translation of the document they want.

***

**Portuguese Translate**
- Criar modelo para solicitar permissão para realizar tradução
**Descrição:** É necessário criar um modelo para os usuários enviarem aos autores para tentar conseguir permissão para realizar uma tradução do documento que desejam.

**Comment by claudiolcastro** [comment]
Como seria esse Template? Seria tipo um formulário e ficaria na pagina do devtranslate.github.io ?

Já tem algo desenhado ou tem que fazer do zero?

**Comment by larismourullo** [comment]
@claudiolcastro basicamente é um texto template para enviar para o criador do conteúdo pedindo permissão para realizar a tradução do conteúdo. Muita gente as vezes gostaria de pedir permissão pra traduzir um conteúdo, mas muitas vezes não sabe como abordar o autor, então ter um template para enviar ajudaria bastante ao realizar. O texto basicamente deveria explicar que a tradução é feita pela comunidade por meio do projeto (devtranslate) e que pretende-se traduzir pra outras línguas o conteúdo, etc. E não infelizmente ainda não existe nada desenhado, seria algo do zero, mas acredito que não seja nada complexo de fazer.

**Comment by larismourullo** [comment]
This issue is solved by @larismourullo. 👍
