### ISSUE TITLE
Translate README to English

### ISSUE THREAD

**Issue by larismourullo** [devtranslate/about#4]
**Progress:**
- To Do ( ✔️)
- In Progress ( ✔️)
- Review ( ✔️)
- Done ( ✔️)

**Repository:**
[devtranslate/medium/README.md](https://github.com/devtranslate/medium/blob/master/README.md)

**Description**
It's necessary to carry out the translation from Portuguese to English of what is already written.

***

**Portuguese Translate**
- Traduzir README para o inglês
**Descrição:** É necessário realizar a tradução do português para o inglês do que já se encontra escrito.

**Comment by flyingluscas** [comment]
I can do that :D

**Comment by larismourullo** [comment]
This issue is solved. **[Pull Request #2](https://github.com/devtranslate/medium/pull/2)**
