### ISSUE TITLE
Translate CONTRIBUTING to English About Files

### ISSUE THREAD

**Issue by larismourullo** [devtranslate/about#8]
**Progress:**
- To Do ( ✔️ )
- In Progress (    )
- Review (    )
- Done (    )

**Repository:**
[devtranslate/about/CONTRIBUTING.md](https://github.com/devtranslate/about/blob/master/CONTRIBUTING.md)

**Description**
It's necessary to carry out the translation from Portuguese to English of what is already written.

***

**Portuguese Translate**
- Traduzir CONTRIBUTING para o inglês
**Descrição:** É necessário realizar a tradução do português para o inglês do que já se encontra escrito.

**Comment by marabesi** [comment]
Seria uma boa terminar a parte de contribuição, eu queria traduzir uns artigos mas não sei como envia-los.

O repo ainda está ativo?

**Comment by larismourullo** [comment]
@marabesi estava um pouco sem tempo para realizar atualizações no projeto, estou vendo se consigo fechar essa semana ainda o contributing, mas se quiser traduzir artigos da uma lida nesse repositório aqui: https://github.com/devtranslate/medium.

**Comment by marabesi** [comment]
show, era isso que eu queria
